export {default as HomePage} from "./HomePage"
export {default as CartPage} from "./CartPage"
export {default as Loading} from "./Loading"
export {default as NotFound} from "./NotFound"
export {default as WishList} from "./WishList"